#!/usr/bin/env bash

DEVICE=$1

#python main.py +scenario=task_incremental_cifar10 +model=resnet20 experiment.experiments=1 +training=cifar10 training.epochs=20 +method=cml_01 +method.dev_split_size=10 optimizer=sgd  training.device="$DEVICE" hydra.run.dir='./results/ablation/ti_cifar10/resnet20/cml/cml_01_dev10'
#python main.py +scenario=task_incremental_cifar10 +model=resnet20 experiment.experiments=1 +training=cifar10 training.epochs=20 +method=cml_01 +method.dev_split_size=50 optimizer=sgd  training.device="$DEVICE" hydra.run.dir='./results/ablation/ti_cifar10/resnet20/cml/cml_01_dev50'
#python main.py +scenario=task_incremental_cifar10 +model=resnet20 experiment.experiments=1 +training=cifar10 training.epochs=20 +method=cml_01 +method.dev_split_size=100 optimizer=sgd  training.device="$DEVICE" hydra.run.dir='./results/ablation/ti_cifar10/resnet20/cml/cml_01_dev100'
#python main.py +scenario=task_incremental_cifar10 +model=resnet20 experiment.experiments=1 +training=cifar10 training.epochs=20 +method=cml_01 +method.dev_split_size=200 optimizer=sgd  training.device="$DEVICE" hydra.run.dir='./results/ablation/ti_cifar10/resnet20/cml/cml_01_dev200'

#python main.py +scenario=class_incremental_cifar10 +model=resnet20 experiment.experiments=1 +training=cifar10 training.epochs=20 +method=cml_01 +method.dev_split_size=0.1 optimizer=sgd  training.device="$DEVICE" hydra.run.dir='./results/ablation/ci_cifar10/resnet20/cml/cml_01_dev01'
#python main.py +scenario=class_incremental_cifar10 +model=resnet20 experiment.experiments=1 +training=cifar10 training.epochs=20 +method=cml_01 +method.dev_split_size=0.05 optimizer=sgd  training.device="$DEVICE" hydra.run.dir='./results/ablation/ci_cifar10/resnet20/cml/cml_01_dev005'
#python main.py +scenario=class_incremental_cifar10 +model=resnet20 experiment.experiments=1 +training=cifar10 training.epochs=20 +method=cml_01 +method.dev_split_size=100 optimizer=sgd  training.device="$DEVICE" hydra.run.dir='./results/ablation/ci_cifar10/resnet20/cml/cml_01_dev100'
#python main.py +scenario=class_incremental_cifar10 +model=resnet20 experiment.experiments=1 +training=cifar10 training.epochs=20 +method=cml_01 +method.dev_split_size=200 optimizer=sgd  training.device="$DEVICE" hydra.run.dir='./results/ablation/ci_cifar10/resnet20/cml/cml_01_dev200'
#python main.py +scenario=class_incremental_cifar10 +model=resnet20 experiment.experiments=1 +training=cifar10 training.epochs=20 +method=cml_01 +method.dev_split_size=50 optimizer=sgd  training.device="$DEVICE" hydra.run.dir='./results/ablation/ci_cifar10/resnet20/cml/cml_01_dev50'
#python main.py +scenario=class_incremental_cifar10 +model=resnet20 experiment.experiments=1 +training=cifar10 training.epochs=20 +method=cml_01 +method.dev_split_size=10 optimizer=sgd  training.device="$DEVICE" hydra.run.dir='./results/ablation/ci_cifar10/resnet20/cml/cml_01_dev10'

#python main.py +scenario=class_incremental_cifar10 +model=resnet20 experiment.experiments=1 +training=cifar10 +method=cml_01 optimizer=sgd +method.proj_w=10 training.device="$DEVICE" hydra.run.dir='./results/ablation/ci_cifar10/resnet20/cml_st/cml_01_10_500'
#python main.py +scenario=class_incremental_cifar10 +model=resnet20 experiment.experiments=1 +training=cifar10 +method=cml_01 optimizer=sgd +method.proj_w=1 training.device="$DEVICE" hydra.run.dir='./results/ablation/ci_cifar10/resnet20/cml_st/cml_01_1_500'
#python main.py +scenario=class_incremental_cifar10 +model=resnet20 experiment.experiments=1 +training=cifar10 +method=cml_01 optimizer=sgd +method.proj_w=0.1 training.device="$DEVICE" hydra.run.dir='./results/ablation/ci_cifar10/resnet20/cml_st/cml_01_01_500'
##python main.py +scenario=class_incremental_cifar10 +model=resnet20 experiment.experiments=1 +training=cifar10 +method=cml_ci_01 optimizer=sgd +method.proj_w=10 training.device="$DEVICE" hydra.run.dir='./results/ablation/ci_cifar10/resnet20/cml_st/cml_01_10_500'
#python main.py +scenario=class_incremental_cifar10 +model=resnet20 experiment.experiments=1 +training=cifar10 +method=cml_01 optimizer=sgd +method.proj_w=0.1 training.device="$DEVICE" hydra.run.dir='./results/ablation/ci_cifar10/resnet20/cml_st/cml_01_01_500'

python main.py +scenario=class_incremental_cifar10 +model=resnet20 +method.sit_memory_size=20 +training=cifar10 +method=cml_01 optimizer=sgd +method.proj_w=1 training.device="$DEVICE" hydra.run.dir='./results/ablation/ci_cifar10/resnet20/cml_newmem/cml_01_1_20' experiment.experiments=1
#python main.py +scenario=class_incremental_cifar10 +model=resnet20 +method.sit_memory_size=100 +training=cifar10 +method=cml_01 optimizer=sgd +method.proj_w=1 training.device="$DEVICE" hydra.run.dir='./results/ablation/ci_cifar10/resnet20/cml_newmem/cml_01_1_50' experiment.experiments=1
python main.py +scenario=class_incremental_cifar10 +model=resnet20 +method.sit_memory_size=50 +training=cifar10 +method=cml_01 optimizer=sgd +method.proj_w=1 training.device="$DEVICE" hydra.run.dir='./results/ablation/ci_cifar10/resnet20/cml_newmem/cml_01_1_50' experiment.experiments=1

python main.py +scenario=class_incremental_cifar10 +model=resnet20 +method.sit_memory_size=20 +training=cifar10 +method=cml_001 optimizer=sgd +method.proj_w=1 training.device="$DEVICE" hydra.run.dir='./results/ablation/ci_cifar10/resnet20/cml_newmem/cml_001_1_20' experiment.experiments=1
#python main.py +scenario=class_incremental_cifar10 +model=resnet20 +method.sit_memory_size=100 +training=cifar10 +method=cml_01 optimizer=sgd +method.proj_w=1 training.device="$DEVICE" hydra.run.dir='./results/ablation/ci_cifar10/resnet20/cml_newmem/cml_01_1_100' experiment.experiments=1
python main.py +scenario=class_incremental_cifar10 +model=resnet20 +method.sit_memory_size=50 +training=cifar10 +method=cml_001 optimizer=sgd +method.proj_w=1 training.device="$DEVICE" hydra.run.dir='./results/ablation/ci_cifar10/resnet20/cml_newmem/cml_001_1_50' experiment.experiments=1

#python main.py +scenario=class_incremental_cifar100 +model=resnet20 +training=cifar100 +method=cml_01 optimizer=sgd +method.proj_w=10 training.device="$DEVICE" hydra.run.dir='./results/ablation/ci_cifar100/resnet20/cml_st/cml_01_10_500'
#python main.py +scenario=class_incremental_cifar100 +model=resnet20  +training=cifar100 +method=cml_01 optimizer=sgd +method.proj_w=1 training.device=4 hydra.run.dir='./results/ablation/ci_cifar100/resnet20/cml_st/cml_01_1_500'
#python main.py +scenario=class_incremental_cifar100 +model=resnet20  +training=cifar100 +method=cml_01 optimizer=sgd +method.proj_w=0.1 training.device="$DEVICE" hydra.run.dir='./results/ablation/ci_cifar100/resnet20/cml_st/cml_01_01_500'
##python main.py +scenario=class_incremental_cifar10 +model=resnet20 experiment.experiments=1 +training=cifar10 +method=cml_ci_01 optimizer=sgd +method.proj_w=10 training.device="$DEVICE" hydra.run.dir='./results/ablation/ci_cifar10/resnet20/cml_st/cml_01_10_500'
#python main.py +scenario=class_incremental_cifar100 +model=resnet20  +training=cifar100 +method=cml_01 optimizer=sgd +method.proj_w=0.1 training.device="$DEVICE" hydra.run.dir='./results/ablation/ci_cifar100/resnet20/cml_st/cml_01_01_500'

#python main.py +scenario=class_incremental_cifar10 +model=resnet20  +training=cifar100 +method=cml_01 optimizer=sgd +method.proj_w=1 method.sit_memory_size=250 training.device="$DEVICE" hydra.run.dir='./results/ablation/ci_cifar100/resnet20/cml_st/cml_01_1_250'
#python main.py +scenario=class_incremental_cifar10 +model=resnet20  +training=cifar100 +method=cml_01 optimizer=sgd +method.proj_w=1 method.sit_memory_size=100 training.device="$DEVICE" hydra.run.dir='./results/ablation/ci_cifar100/resnet20/cml_st/cml_01_1_100'
#python main.py +scenario=class_incremental_cifar10 +model=resnet20  +training=cifar100 +method=cml_01 optimizer=sgd +method.proj_w=1  method.sit_memory_size=50 training.device="$DEVICE" hydra.run.dir='./results/ablation/ci_cifar100/resnet20/cml_st/cml_01_1_50'

#python main.py +scenario=class_incremental_cifar100 +model=resnet20 experiment.experiments=1  training.batch_size=32 +training=cifar100 training.epochs=20 +method=cml_ci_001 optimizer=sgd  training.device="$DEVICE" hydra.run.dir='./results/ablation/ci_cifar100/resnet20/cml/cml_001_dev01'
#python main.py +scenario=class_incremental_cifar100 +model=resnet20 experiment.experiments=1 training.batch_size=32 +training=cifar100 training.epochs=20 +method=cml_ci_001 method.sit_memory_size=200 optimizer=sgd   training.device="$DEVICE"   hydra.run.dir='./results/ablation/ci_cifar100/resnet20/cml/cml_001_dev02'
#python main.py +scenario=class_incremental_cifar100 +model=resnet20 experiment.experiments=1  training.batch_size=32 +training=cifar100 training.epochs=20 +method=cml_ci_001 method.sit_memory_size=100 optimizer=sgd   training.device="$DEVICE" hydra.run.dir='./results/ablation/ci_cifar100/resnet20/cml/cml_001_dev03'
#python main.py +scenario=class_incremental_cifar100 +model=resnet20 experiment.experiments=1 training.batch_size=32 +training=cifar100 training.epochs=20 +method=cml_ci_001 method.sit_memory_size=300 optimizer=sgd   training.device="$DEVICE" hydra.run.dir='./results/ablation/ci_cifar100/resnet20/cml/cml_001_dev04'

#python main.py +scenario=class_incremental_cifar100 +model=resnet20 experiment.experiments=1  training.batch_size=32 +training=cifar100 training.epochs=20 +method=cml_ci_001 optimizer=sgd  training.device="$DEVICE" method.penalty_weight=0.1 hydra.run.dir='./results/ablation/ci_cifar100/resnet20/cml/cml_01_dev01'
#python main.py +scenario=class_incremental_cifar100 +model=resnet20 experiment.experiments=1 training.batch_size=32 +training=cifar100 training.epochs=20 +method=cml_ci_001 method.sit_memory_size=200 optimizer=sgd   training.device="$DEVICE"  method.penalty_weight=0.1 hydra.run.dir='./results/ablation/ci_cifar100/resnet20/cml/cml_01_dev02'
#python main.py +scenario=class_incremental_cifar100 +model=resnet20 experiment.experiments=1  training.batch_size=32 +training=cifar100 training.epochs=20 +method=cml_ci_001 method.sit_memory_size=100 optimizer=sgd   training.device="$DEVICE" method.penalty_weight=0.1 hydra.run.dir='./results/ablation/ci_cifar100/resnet20/cml/cml_01_dev03'
#python main.py +scenario=class_incremental_cifar100 +model=resnet20 experiment.experiments=1 training.batch_size=32 +training=cifar100 training.epochs=20 +method=cml_ci_001 method.sit_memory_size=300 optimizer=sgd   training.device="$DEVICE" method.penalty_weight=0.1 hydra.run.dir='./results/ablation/ci_cifar100/resnet20/cml/cml_01_dev04'
#
#python main.py +scenario=class_incremental_cifar100 +model=resnet20 experiment.experiments=1  training.batch_size=32 +training=cifar100 training.epochs=20 +method=cml_ci_001 optimizer=sgd  training.device="$DEVICE" method.penalty_weight=1 hydra.run.dir='./results/ablation/ci_cifar100/resnet20/cml/cml_1_dev01'
#python main.py +scenario=class_incremental_cifar100 +model=resnet20 experiment.experiments=1 training.batch_size=32 +training=cifar100 training.epochs=20 +method=cml_ci_001 method.sit_memory_size=200 optimizer=sgd   training.device="$DEVICE"  method.penalty_weight=1 hydra.run.dir='./results/ablation/ci_cifar100/resnet20/cml/cml_1_dev02'
#python main.py +scenario=class_incremental_cifar100 +model=resnet20 experiment.experiments=1  training.batch_size=32 +training=cifar100 training.epochs=20 +method=cml_ci_001 method.sit_memory_size=100 optimizer=sgd   training.device="$DEVICE" method.penalty_weight=1 hydra.run.dir='./results/ablation/ci_cifar100/resnet20/cml/cml_1_dev03'
#python main.py +scenario=class_incremental_cifar100 +model=resnet20 experiment.experiments=1 training.batch_size=32 +training=cifar100 training.epochs=20 +method=cml_ci_001 method.sit_memory_size=300 optimizer=sgd   training.device="$DEVICE" method.penalty_weight=1 hydra.run.dir='./results/ablation/ci_cifar100/resnet20/cml/cml_1_dev04'
