#!/usr/bin/env bash

DEVICE=$1

#python main.py +scenario=class_incremental_cifar10 +model=resnet20 +training=cifar10 +method=cml_01 optimizer=sgd +method.proj_w=1 training.device="$DEVICE" hydra.run.dir='./results/ablation/epochs_batch_size/ci_cifar10/resnet20/cml/20_32' experiment.experiments=1 method.memory_parameters.memory_size=500 +scenario.shuffle_first=true 
#python main.py +scenario=class_incremental_cifar10 +model=resnet20 +training=cifar10 +method=cml_01 optimizer=sgd +method.proj_w=1 training.device="$DEVICE" hydra.run.dir='./results/ablation/epochs_batch_size/ci_cifar10/resnet20/cml/20_64' experiment.experiments=1 method.memory_parameters.memory_size=500 +scenario.shuffle_first=true  training.batch_size=64
#python main.py +scenario=class_incremental_cifar10 +model=resnet20 +training=cifar10 +method=cml_01 optimizer=sgd +method.proj_w=1 training.device="$DEVICE" hydra.run.dir='./results/ablation/epochs_batch_size/ci_cifar10/resnet20/cml/20_16' experiment.experiments=1 method.memory_parameters.memory_size=500 +scenario.shuffle_first=true  training.batch_size=16

python main.py +scenario=class_incremental_cifar10 +model=resnet20 +training=cifar10 +method=cml_01 optimizer=sgd +method.proj_w=1 training.device="$DEVICE" hydra.run.dir='./results/ablation/epochs_batch_size/ci_cifar10/resnet20/cml/5_32' experiment.experiments=1 method.memory_parameters.memory_size=500 +scenario.shuffle_first=true  training.epochs=5
python main.py +scenario=class_incremental_cifar10 +model=resnet20 +training=cifar10 +method=cml_01 optimizer=sgd +method.proj_w=1 training.device="$DEVICE" hydra.run.dir='./results/ablation/epochs_batch_size/ci_cifar10/resnet20/cml/5_64' experiment.experiments=1 method.memory_parameters.memory_size=500 +scenario.shuffle_first=true  training.batch_size=64 training.epochs=5
python main.py +scenario=class_incremental_cifar10 +model=resnet20 +training=cifar10 +method=cml_01 optimizer=sgd +method.proj_w=1 training.device="$DEVICE" hydra.run.dir='./results/ablation/epochs_batch_size/ci_cifar10/resnet20/cml/5_16' experiment.experiments=1 method.memory_parameters.memory_size=500 +scenario.shuffle_first=true  training.batch_size=16 training.epochs=5

python main.py +scenario=class_incremental_cifar10 +model=resnet20 +training=cifar10 +method=cml_01 optimizer=sgd +method.proj_w=1 training.device="$DEVICE" hydra.run.dir='./results/ablation/epochs_batch_size/ci_cifar10/resnet20/cml/10_32' experiment.experiments=1 method.memory_parameters.memory_size=500 +scenario.shuffle_first=true  training.epochs=10
python main.py +scenario=class_incremental_cifar10 +model=resnet20 +training=cifar10 +method=cml_01 optimizer=sgd +method.proj_w=1 training.device="$DEVICE" hydra.run.dir='./results/ablation/epochs_batch_size/ci_cifar10/resnet20/cml/10_64' experiment.experiments=1 method.memory_parameters.memory_size=500 +scenario.shuffle_first=true  training.batch_size=64 training.epochs=10
python main.py +scenario=class_incremental_cifar10 +model=resnet20 +training=cifar10 +method=cml_01 optimizer=sgd +method.proj_w=1 training.device="$DEVICE" hydra.run.dir='./results/ablation/epochs_batch_size/ci_cifar10/resnet20/cml/10_16' experiment.experiments=1 method.memory_parameters.memory_size=500 +scenario.shuffle_first=true  training.batch_size=16 training.epochs=10

python main.py +scenario=class_incremental_cifar10 +model=resnet20 +training=cifar10 +method=cml_01 optimizer=sgd +method.proj_w=1 training.device="$DEVICE" hydra.run.dir='./results/ablation/epochs_batch_size/ci_cifar10/resnet20/cml/20_32' experiment.experiments=1 method.memory_parameters.memory_size=500 +scenario.shuffle_first=true  training.epochs=20
python main.py +scenario=class_incremental_cifar10 +model=resnet20 +training=cifar10 +method=cml_01 optimizer=sgd +method.proj_w=1 training.device="$DEVICE" hydra.run.dir='./results/ablation/epochs_batch_size/ci_cifar10/resnet20/cml/20_64' experiment.experiments=1 method.memory_parameters.memory_size=500 +scenario.shuffle_first=true  training.batch_size=64 training.epochs=20
python main.py +scenario=class_incremental_cifar10 +model=resnet20 +training=cifar10 +method=cml_01 optimizer=sgd +method.proj_w=1 training.device="$DEVICE" hydra.run.dir='./results/ablation/epochs_batch_size/ci_cifar10/resnet20/cml/20_16' experiment.experiments=1 method.memory_parameters.memory_size=500 +scenario.shuffle_first=true  training.batch_size=16 training.epochs=20
